// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TermProject.Models;

namespace TermProject.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20201207020356_Initia")]
    partial class Initia
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TermProject.Models.Candidates", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("ID")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nchar(15)")
                        .IsFixedLength(true)
                        .HasMaxLength(15);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nchar(15)")
                        .IsFixedLength(true)
                        .HasMaxLength(15);

                    b.Property<int?>("PartyId")
                        .HasColumnName("PartyID")
                        .HasColumnType("int");

                    b.Property<int>("StateId")
                        .HasColumnName("StateID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartyId");

                    b.HasIndex("StateId");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("TermProject.Models.Party", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("ID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true)
                        .HasMaxLength(10);

                    b.Property<int>("YearFormed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Party");
                });

            modelBuilder.Entity("TermProject.Models.State", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("ID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nchar(15)")
                        .IsFixedLength(true)
                        .HasMaxLength(15);

                    b.HasKey("Id");

                    b.ToTable("State");
                });

            modelBuilder.Entity("TermProject.Models.Candidates", b =>
                {
                    b.HasOne("TermProject.Models.Party", "Party")
                        .WithMany("Candidates")
                        .HasForeignKey("PartyId")
                        .HasConstraintName("FK_PartyID");

                    b.HasOne("TermProject.Models.State", "State")
                        .WithMany("Candidates")
                        .HasForeignKey("StateId")
                        .HasConstraintName("FK_StateID")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
